"""Generates the backtesting report."""

from __future__ import annotations

from typing import TYPE_CHECKING

import pandas as pd

from creditsurv.reporting import charts
from creditsurv.reporting.builder import Report, provenance

if TYPE_CHECKING:
    from pathlib import Path

    from creditsurv.backtest.runner import BacktestResult
    from creditsurv.backtest.splits import Split


def generate(split: Split, result: BacktestResult, *, reports_dir: Path) -> Path:
    """Write ``backtesting.md`` and its figure."""
    figures = reports_dir / "figures"
    report = Report(
        "Backtesting",
        subtitle="Generated by `creditsurv report`. Numbers come from the run, not the prose.",
    )

    report.heading("What is being tested").text(
        f"""
One cut, in calendar time, at **{result.as_of}**. Everything observed at or before it
fits the model; everything after it judges it. There is no second fit anywhere in this
report — the model scored below is the same one the methodology and calibration
reports describe, and it has never seen a month of the test window.

That is a deliberate narrowing. An earlier version refitted at several reporting dates
and again under two macroeconomic assumptions, which answers a richer question at a
cost of eight fits; on this panel a fit is hours rather than seconds, and the richer
question was not the one being asked.

**Why the cut is in calendar time and not by loan.** Holding out random loans still
trains the model on the calendar periods it is about to be judged on, so it has
already seen the macro conditions of the test window. That is look-ahead even though
no loan appears on both sides of the line, and it flatters the result exactly where
the model is weakest — in the downturns nobody had seen yet.

**The cut is late on purpose.** A credit model wants every loan-month it can get, and
holding back a decade to see the same answer at four dates is a poor trade.
"""
    ).table(
        pd.DataFrame([split.describe()]),
        caption="Exposure either side of the reporting date",
    )

    report.heading("Predicted against realised").text(
        """
Expected defaults are the sum of the model's monthly hazard times the loan-months
each cell stands for. Actual defaults are the loan-months the data records as ending
in default. The ratio is the number a credit committee reads: **above one the model
under-predicted**, below one it over-predicted.

There is no forward projection. A cell already records what its loans looked like in
the month it covers, so the prediction is evaluated there — which is simpler than
projecting a book forward and closer to the question being asked.
"""
    ).key_values(
        {
            "loan-months scored": f"{result.loan_months:,}",
            "expected defaults": f"{result.expected_defaults:,.0f}",
            "actual defaults": f"{result.actual_defaults:,.0f}",
            "actual / expected": f"{result.actual_over_expected:.4f}",
            "Gini (exposure-weighted)": f"{result.gini:.4f}",
        }
    )

    if not result.over_time.empty:
        figure = charts.backtest_over_time(result.over_time, figures / "backtest_over_time.png")
        report.figure(figure, "Predicted and realised default rate through the test window")
        report.table(
            result.over_time.iloc[:: max(len(result.over_time) // 12, 1)],
            caption="By month of observation",
            decimals=6,
        )

    report.heading("Calibration by decile of predicted risk").text(
        """
Buckets are quantiles of **exposure**, not of rows, so each holds a comparable slice
of the book rather than a comparable number of cells — which would be a property of
the binning rather than of the portfolio.

A model can be excellent here and useless at ranking, or the reverse. Both are
reported because they fail independently.
"""
    ).table(result.calibration, decimals=6)

    if not result.calibration.empty:
        figure = charts.calibration(result.calibration, figures / "calibration.png")
        report.figure(figure, "Realised against predicted default rate, by decile")

    report.heading("Discrimination").text(
        f"""
**Gini {result.gini:.4f}**, from the exposure-weighted Lorenz curve.

A concordance index is not available and the substitution is not a convenience: the
index needs pairs of *subjects*, and an aggregated cell is not a subject. The Lorenz
construction asks the equivalent question of the data that does exist — order the
cells by predicted risk and see how much realised default falls in the riskiest slice
of exposure — and lands on the same zero-to-one scale.

What is genuinely lost is the ability to say the model ranks *loans*. It ranks
exposure, which is what an aggregated panel can support.
"""
    )

    if not result.stability.empty:
        report.heading("Population stability").text(
            """
How far each covariate's distribution moved across the cut, weighted by exposure.

The usual reading — below 0.1 stable, 0.1 to 0.25 monitor, above 0.25 shifted — was
devised for **application characteristics**: credit score, loan size, the mix of
business being written. It does not transfer to macro-driven covariates, which are
*designed* to move with the economy and whose index is large whenever anything
happened. Those rows are labelled rather than dropped, so the alarming figure is
visible and correctly discounted instead of quietly triggering a model review.
"""
        ).table(result.stability, decimals=4)

    report.heading("What this backtest does not measure").text(
        """
**The macro path is the one that actually occurred.** That is what *predicted against
realised* means, and it grants the model something a real deployment would not have:
a model used in anger has to forecast the economy, and its error includes that
forecast's error. This isolates the credit model. Reading it as the performance of the
whole system would overstate what the system can do.

A previous version quantified that gap by scoring twice, once on the realised path and
once on a random walk from the reporting date. It was removed with the rest of the
extra fitting; the gap it measured was real and is not measured here.

**Prepayment is treated as independent censoring**, so a loan that leaves the book
before the end of the window is not counted against the model. It is really a
competing risk, and the direction of the bias is upward on lifetime PD.
"""
    )

    report.text(
        provenance(
            [
                "`uv run creditsurv report`",
                f"Reporting date: {result.as_of}",
                f"Training exposure: {split.describe()['train_loan_months']:,} loan-months",
                f"Test exposure: {result.loan_months:,} loan-months",
            ]
        )
    )
    return report.write(reports_dir / "backtesting.md")
