"""Generates the backtesting report."""

from __future__ import annotations

from typing import TYPE_CHECKING

from creditsurv.backtest.runner import macro_mode_gap
from creditsurv.reporting import charts
from creditsurv.reporting.builder import Report, provenance

if TYPE_CHECKING:
    from collections.abc import Sequence
    from pathlib import Path

    import pandas as pd

    from creditsurv.backtest.runner import BacktestResult


def generate(
    summary: pd.DataFrame,
    results: Sequence[BacktestResult],
    *,
    reports_dir: Path,
) -> Path:
    """Write ``backtesting.md`` and its figures."""
    figures = reports_dir / "figures"
    report = Report(
        "Backtesting",
        subtitle="Generated by `creditsurv report`. Numbers come from the run, not the prose.",
    )

    report.heading("Split design").text(
        """
A random split is the wrong default. A credit model is used to write business that
does not exist yet, in an economy that has not happened yet, so the question is
never whether a held-out row can be predicted but whether the model holds up on a
later cohort, or in a later year.

**Every split is truncated in calendar time.** Training on the full history of an
early vintage means training on calendar periods that overlap the test window, so
the model has already seen the conditions it is about to be judged on. That is
look-ahead even though no loan appears in both halves, and it flatters the result
exactly where the model is weakest -- during downturns nobody had seen yet.
"""
    ).bullets(
        [
            "**Out-of-time** -- train on everything known by the reporting date, "
            "test on cohorts written after it. The hardest and most realistic test.",
            "**Out-of-sample** -- a random holdout from the same period. Deliberately "
            "the easy split: it isolates estimation noise from regime change, so the "
            "gap between it and out-of-time says how much of any degradation is the "
            "economy moving rather than the sample being small.",
            "**Walk-forward** -- the as-of split repeated at successive reporting "
            "dates with an expanding window. One holdout says how the model did in "
            "one regime; several say whether that was a fluke.",
        ]
    )

    report.heading("The two macro modes").text(
        """
**Conditional** feeds the macro path that actually occurred over the test window,
isolating the credit model: given the right economy, does it rank and price
correctly?

**Unconditional** feeds only what was knowable at the reporting date -- a random
walk from the last observation -- and tests the whole system as it would really have
been used, macro forecasting error included.

Reporting only the first overstates what the model can do. Reporting only the
second blames the credit model for the impossibility of forecasting the economy.
The gap between them attributes the error.

We have no vintage-dated macro forecasts, so the unconditional mode uses a random
walk. That is an approximation rather than a reconstruction of what a forecaster
would have said at the time, and it is recorded as one.
"""
    )

    report.heading("Results").table(summary, decimals=4)

    if not summary.empty and "concordance" in summary.columns:
        figure = charts.backtest_discrimination(summary, figures / "backtest_discrimination.png")
        report.figure(figure, "Concordance by reporting date and macro mode")

    concordance_gap = macro_mode_gap(summary, "concordance")
    calibration_gap = macro_mode_gap(summary, "actual_over_expected")

    report.heading("Where knowing the economy actually matters").text(
        """
The gap between the macro modes appears in **calibration and not in
discrimination**. That is what should happen: a macro path shifts every loan's PD
in the same direction, so the ranking survives and the level does not.

It is worth stating because the natural instinct is to check discrimination first,
and doing so here would conclude that macro forecasting does not matter -- a
statement about the tool rather than about the model.
"""
    ).table(concordance_gap, caption="Discrimination gap (concordance)", decimals=4)
    report.table(calibration_gap, caption="Calibration gap (actual over expected)", decimals=4)

    scored = [result for result in results if not result.calibration.empty]
    if scored:
        first = scored[0]
        figure = charts.calibration(first.calibration, figures / "calibration.png")
        report.heading("Calibration by decile of predicted risk").text(
            f"""
Buckets are quantiles of the prediction, so each holds a similar number of loans
and the tail buckets -- where a model earns or loses its money -- are not one loan
wide. Shown for `{first.split}` under the `{first.macro_mode.value}` macro path.
"""
        ).figure(figure, "Realised against predicted default rate by decile")
        report.table(first.calibration, caption="Actual against expected by decile")

        report.heading("Population stability").text(
            """
The conventional thresholds -- below 0.1 stable, above 0.25 shifted -- were devised
for **application characteristics**: score, loan size, business mix. Those should
look much the same quarter to quarter, and a jump means something changed about who
is applying.

They do not transfer to macro-driven covariates, which are *designed* to move with
the economy. Train and test come from different calendar periods by construction,
so those covariates score high whenever anything happened. They are labelled rather
than scored, so the figure stays visible and correctly discounted instead of
quietly triggering a model review.
"""
        ).table(first.stability, decimals=4)

    report.text(
        provenance(
            [
                "`uv run creditsurv backtest` / `creditsurv report`",
                f"{len(results)} split-mode combinations evaluated",
                "Loan data: Freddie Mac Single-Family Loan-Level Dataset. "
                "Macroeconomic series: FRED.",
            ]
        )
    )
    return report.write(reports_dir / "backtesting.md")
