"""Generates the calibration report: what the regressors are worth.

"Calibration" means two different things in credit risk and both belong here, so
each is labelled:

**Parameter estimation** -- what each regressor is worth, its uncertainty, and what
a unit of it does to the probability of default.

**Predictive calibration** -- whether predicted default rates match realised ones.

A model can be excellent at the second and meaningless at the first, and vice
versa. Reporting one as though it were the other is a common way to overstate a
model.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import pandas as pd

from creditsurv.models.aft import coefficient_table
from creditsurv.models.lifetime_pd import (
    conditional_pd,
    extend_macro,
    pd_term_structure,
    project_panel,
    scenario_lifetime_pd,
    survival_along_path,
)
from creditsurv.reporting import charts
from creditsurv.reporting.builder import Report, provenance

if TYPE_CHECKING:
    from collections.abc import Sequence
    from pathlib import Path

    from creditsurv.models.aft import FitResult

#: A one standard deviation move is the comparison a credit committee can read.
#: Raw coefficients are not comparable across covariates measured in different units.
_SHOCK_SIGMAS = 1.0


def marginal_effects(
    fitted: FitResult,
    loans: pd.DataFrame,
    macro: pd.DataFrame,
    covariates: Sequence[str],
    continuous: Sequence[str],
    *,
    horizon_months: int = 12,
) -> pd.DataFrame:
    """Change in PD from a one standard deviation move in each covariate.

    Coefficients are not comparable across covariates measured in different units,
    and a time ratio is not what a credit decision is denominated in. This
    re-expresses each effect as the change in probability of default it produces,
    holding everything else where it is.
    """
    extended = extend_macro(macro, horizon_months + 2)
    baseline_panel = project_panel(loans, extended, horizon_months=horizon_months)
    baseline = conditional_pd(survival_along_path(fitted, baseline_panel, covariates)).mean()

    rows = []
    for name in continuous:
        if name not in loans.columns and name not in baseline_panel.columns:
            continue
        shifted = loans.copy()
        source = baseline_panel[name] if name in baseline_panel.columns else loans[name]
        step = float(source.std()) * _SHOCK_SIGMAS
        if name in shifted.columns:
            shifted[name] = shifted[name] + step
            panel = project_panel(shifted, extended, horizon_months=horizon_months)
        else:
            panel = baseline_panel.copy()
            panel[name] = panel[name] + step

        shocked = conditional_pd(survival_along_path(fitted, panel, covariates)).mean()
        rows.append(
            {
                "covariate": name,
                "one_sd": step,
                "baseline_pd": float(baseline),
                "shocked_pd": float(shocked),
                "change_pp": float(shocked - baseline) * 100.0,
            }
        )

    table = pd.DataFrame(rows)
    return table.reindex(table["change_pp"].abs().sort_values(ascending=False).index)


def generate(
    fitted: FitResult,
    loans: pd.DataFrame,
    macro: pd.DataFrame,
    covariates: Sequence[str],
    continuous: Sequence[str],
    *,
    reports_dir: Path,
    horizon_months: int = 60,
) -> Path:
    """Write ``calibration.md`` and its figures."""
    figures = reports_dir / "figures"
    report = Report(
        "Calibration: what the regressors are worth",
        subtitle="Generated by `creditsurv report`. Numbers come from the run, not the prose.",
    )

    report.heading("Reading an AFT coefficient").text(
        """
This is an **accelerated failure time** model, so a coefficient acts on the
logarithm of survival *time*. A positive coefficient lengthens expected survival
and therefore **lowers** risk.

`exp(coef)` is consequently a **time ratio**, not a hazard ratio. A time ratio of
1.4 means a loan is expected to last forty percent longer, not that it is forty
percent more likely to default. Reading the column as a hazard ratio inverts the
sign of every conclusion in this report, which is why the table below names it for
what it is.
"""
    )

    table = coefficient_table(fitted)
    figure = charts.coefficients(table, figures / "coefficients.png")
    report.heading("Coefficient estimates").table(
        table.reset_index(), caption="Coefficients on log survival time", decimals=4
    ).figure(figure, "Coefficient estimates with 95% confidence intervals")

    report.text(
        """
Interpretation of the two parameter blocks: `lambda_` carries the covariate effects
on the scale of survival time, while `rho_` is the shape of the baseline hazard. A
`rho_` intercept above zero means the hazard *rises* with loan age, which is the
seasoning pattern mortgages are expected to show.
"""
    )

    effects = marginal_effects(fitted, loans, macro, covariates, continuous)
    report.heading("Marginal effects on probability of default").text(
        """
Coefficients are not comparable across covariates measured in different units, and
a time ratio is not the currency a credit decision is made in. Each row below moves
one covariate by one standard deviation and reports the change in twelve-month PD
in percentage points, holding everything else where it is.
"""
    ).table(effects, decimals=4)

    extended = extend_macro(macro, horizon_months + 2)
    panel = project_panel(loans, extended, horizon_months=horizon_months)
    survival = survival_along_path(fitted, panel, covariates)
    structure = pd_term_structure(survival)

    structure_figure = charts.term_structure(structure, figures / "term_structure.png")
    report.heading("PD term structure").text(
        """
Two portfolios can share a lifetime PD and differ entirely here, and the difference
decides when losses arrive. The cumulative and marginal series are shown in
separate panels rather than on a shared frame with two y-axes: they differ by an
order of magnitude, and a second axis lets the choice of scales decide how related
the two appear.
"""
    ).figure(structure_figure, "Cumulative and marginal PD by month")
    report.table(
        structure.reset_index().iloc[:: max(len(structure) // 12, 1)],
        caption="Term structure, sampled across the horizon",
    )

    report.key_values(
        {
            "12-month PD": float(conditional_pd(survival, horizon_months=12).mean()),
            f"lifetime PD ({horizon_months}m)": float(conditional_pd(survival).mean()),
        }
    )

    scenarios = scenario_lifetime_pd(
        fitted, loans, macro, covariates, horizon_months=min(horizon_months, 36)
    )
    scenario_figure = charts.scenario_comparison(scenarios, figures / "scenarios.png")
    uplift = float(scenarios["adverse"].mean() / scenarios["baseline"].mean())

    report.heading("Macroeconomic scenarios").text(
        f"""
The adverse path is shaped like 2008 rather than scaled to it: unemployment climbs
over a year and stays high, house prices fall for two years, credit tightens. The
baseline is a random walk from the last observation, which is **not a forecast** and
is not offered as one -- it is what makes the relative effect of a scenario
interpretable without smuggling in a view on the economy.

Because the covariates are time-varying, the scenario is applied by projecting the
covariate paths and chaining conditional survival, not by re-scoring frozen
covariates. That distinction is the whole exercise: an earlier version of this code
advanced calendar time from each loan's origination rather than from the reporting
date, so the projected macro path was never reached and both scenarios returned
almost the same answer. The model looked stable when it was simply not being asked
the question.

**Adverse lifetime PD is {uplift:.2f}x the baseline.**
"""
    ).figure(scenario_figure, "Distribution of lifetime PD under each scenario")
    report.table(
        scenarios.describe().reset_index(names="statistic"),
        caption="Lifetime PD by scenario",
    )

    report.text(
        provenance(
            [
                "`uv run creditsurv report`",
                f"Distribution: {fitted.distribution}; likelihood: {fitted.likelihood.value}",
                f"Loans scored: {len(loans)}; horizon: {horizon_months} months",
            ]
        )
    )
    return report.write(reports_dir / "calibration.md")
