"""The distribution family, chosen by the rule written before either family was fitted.

Rule 2 of `docs/rules.md`: both families go through the whole selection, and the winner is
the one whose **selected model** sits closest to the non-parametric cumulative incidence of
default -- Aalen-Johansen, which accounts for prepayment as a competing risk -- over the loan
ages carrying at least 100,000 loan-months. A family whose selected model turns a declared
sign is excluded whatever its fit, and inside a tenth of a percentage point the Weibull is
kept.

The likelihood is deliberately not the criterion. On the specification before the validation
the Weibull led by 623,126 AIC points; on the one after it the log-logistic led by 83,961,
and the two models disagree about the hazard at long ages by more than either disagrees with
the data at short ones. A criterion that changes its mind with the specification is not a
criterion, and AIC on 72 million episodes measures fit where the data is dense -- the first
few years -- which is not where a lifetime PD spends its time.

**The prepayment hazard is held fixed** across the comparison, at the one the Weibull
selection chose. The cumulative incidence needs both cause-specific hazards, and letting
both vary would compare four models in pairs while the rule speaks about one. What varies
here is the default model, which is what the rule is about.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import pandas as pd

from creditsurv.models.nonparametric import EXPOSURE_FLOOR
from creditsurv.models.selection import (
    FAMILY_ON_A_TIE,
    FAMILY_TIE,
    family_by_the_rule,
    family_comparison,
)
from creditsurv.reporting.builder import Report, provenance

if TYPE_CHECKING:
    from collections.abc import Mapping, Sequence
    from pathlib import Path


def generate(
    gaps: Mapping[str, pd.DataFrame],
    signs: Mapping[str, Sequence[str]],
    *,
    formulas: Mapping[str, str],
    reports_dir: Path,
) -> tuple[str, Path]:
    """Write ``family.md``, and return the family the rule chose.

    ``gaps`` maps each family to the table :func:`creditsurv.models.nonparametric.incidence_gap`
    produced for its selected model, ``signs`` to the covariates that model turns against a
    declared prior, and ``formulas`` to what each selection ended on.
    """
    reports_dir.mkdir(parents=True, exist_ok=True)
    comparison = family_comparison(gaps, signs)
    chosen, why = family_by_the_rule(comparison)

    report = Report(
        "The distribution family",
        subtitle="Generated by `creditsurv family`. Every number comes from this run.",
    )
    report.heading("The rule, before the fits").text(
        f"""
Both families are taken through the whole selection, and the winner is the one whose
**selected model** sits closest to the Aalen-Johansen cumulative incidence of default, in
mean absolute percentage points, over the loan ages carrying at least
{EXPOSURE_FLOOR:,.0f} loan-months. A family whose selected model turns a declared sign is
excluded whatever its fit: a model that says tighter financial conditions lengthen survival
is not a better model, it is a broken one. Inside {FAMILY_TIE:g} percentage points the
{FAMILY_ON_A_TIE} is kept, because its hazard does not fall at long ages and the families
differ most exactly where the data ends and the extrapolation begins.

The likelihood is not the criterion, and not because it is inconvenient: it changed its mind
between two specifications of this same model, by 623,126 AIC points one way and 83,961 the
other.
"""
    )

    report.heading("What each family chose").table(
        pd.DataFrame(
            [{"distribution": name, "formula": formula} for name, formula in formulas.items()]
        ),
        caption="Each family's own selection, not one specification fitted twice",
    )

    report.heading("How far each sits from the observed incidence").table(
        comparison,
        caption="Mean and worst absolute gap in percentage points, over the ages compared",
    )

    report.heading("The verdict").text(f"**{chosen}.** {why[0].upper()}{why[1:]}.")
    for name, table in gaps.items():
        report.heading(f"{name}: the gap age by age", level=3).table(
            table.iloc[:: max(len(table) // 40, 1)],
            caption="Every fortieth age, to keep the table readable",
            decimals=4,
        )

    report.text(
        provenance(
            [
                "`uv run creditsurv select --dist weibull` and `--dist loglogistic`",
                "Rule: `docs/rules.md`, section 2",
                "Applied by: `creditsurv.models.selection.family_by_the_rule`",
            ]
        )
    )
    return chosen, report.write(reports_dir / "family.md")
