"""Generates the methodology and fit-quality report.

Covers why the model is specified the way it is, how the distributional form was
chosen, and how well the result fits -- including the parts of the plan that did
not survive contact with the data, since a selection procedure is only credible if
its failures are visible too.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np

from creditsurv.config import CATEGORICAL_REFERENCE
from creditsurv.models.nonparametric import (
    kaplan_meier,
    km_band_contains,
    predicted_survival_curve,
)
from creditsurv.models.selection import (
    SHAPE_COVARIATE,
    distribution_comparison,
    exponential_is_rejected,
    marginal_comparison,
    shape_depends_on_covariates,
    shape_formula,
)
from creditsurv.reporting import charts
from creditsurv.reporting.builder import Report, provenance

if TYPE_CHECKING:
    from collections.abc import Sequence
    from pathlib import Path

    import pandas as pd

    from creditsurv.models.aft import FitResult


def _pct(band: pd.DataFrame, month: int, column: str) -> str:
    """One band edge, as a percentage, for the narrowness illustration."""
    position = int(np.argmin(np.abs(band.index.to_numpy(dtype=float) - month)))
    return f"{float(band[column].to_numpy()[position]):.4f}"


def _band_width(band: pd.DataFrame, month: int) -> float:
    """Width of the confidence band at one month, in percentage points."""
    position = int(np.argmin(np.abs(band.index.to_numpy(dtype=float) - month)))
    return float(band["band_width"].to_numpy()[position] * 100.0)


def _median_width(band: pd.DataFrame) -> float:
    """Median width across the horizon, in percentage points."""
    return float(band["band_width"].median() * 100.0)


def _worst(band: pd.DataFrame) -> float:
    """Largest absolute gap between the fitted curve and observed survival, in points."""
    return float(band["deviation"].abs().max() * 100.0)


def _mean_deviation(band: pd.DataFrame) -> float:
    return float(band["deviation"].abs().mean() * 100.0)


def _direction(rho: float) -> str:
    """How the Weibull hazard moves with age, read off its shape parameter.

    Stated rather than asserted: a report that says "the hazard rises" while its own
    number says otherwise is worse than one that says nothing.
    """
    if rho > 1.0:
        return "**rises** with loan age, which is the seasoning pattern mortgages are expected to "
    if rho < 1.0:
        return "**falls** with loan age, which is *not* the seasoning pattern mortgages usually "
    return "is constant in loan age, so the exponential is not rejected and is the simpler "


#: What a skipped section says instead of quietly disappearing. A report missing a
#: section reads as a report whose author had nothing to say about it.
_SKIPPED = (
    "> **Not run.** {what} costs a fit of its own, which on the whole population is "
    "hours rather than seconds. Re-run with `{flag}` to compute it."
)


def generate(
    panel: pd.DataFrame,
    encoded: pd.DataFrame,
    fitted: FitResult,
    covariates: Sequence[str],
    formula: str,
    *,
    reports_dir: Path,
    weights_col: str | None = None,
    extra_fits: bool = True,
) -> Path:
    """Write ``methodology.md`` and its figures.

    ``weights_col`` names the loan-month count carried by an aggregated panel. Every
    statistic below then describes the population rather than the set of distinct
    covariate combinations, which are very different books.

    ``extra_fits`` controls the two sections that cost a fit of their own: the
    distributional comparison and the shape test. Both are model *selection*, so they
    belong in a report about methodology -- and on the whole population each is hours,
    which is a reason to be able to skip them, not a reason to pretend they were run.
    A skipped section says so in the report rather than vanishing from it.
    """
    figures = reports_dir / "figures"

    report = Report(
        "Methodology, variable selection and fit quality",
        subtitle="Generated by `creditsurv report`. Numbers come from the run, not the prose.",
    )

    report.heading("Why survival analysis").text(
        """
A default flag answers whether a loan defaulted. Lifetime PD needs to know *when*,
and needs an answer for the loans that have not defaulted yet -- which is most of
them. A classifier discards both: the timing, and the fact that a loan observed for
six months and still performing is evidence about the first six months only.

Survival analysis keeps both. Censoring is a first-class concept rather than a
missing label, and the output is a curve rather than a number, which is what a term
structure of losses is built from.
"""
    )

    report.heading("Why a parametric model rather than Cox").text(
        """
Lifetime PD needs three things a Cox model does not give:

1. **Extrapolation past the observation window.** A Cox baseline hazard is defined
   only where events were observed; a lifetime PD quoted over a remaining term
   longer than the data has seen requires a functional form.
2. **Response to macroeconomic scenarios.** Pushing a stressed macro path through
   the model requires a hazard that can be evaluated at covariate values that have
   not occurred.
3. **A smooth term structure.** A step function is an awkward basis for a loss
   forecast by month.

The cost is an assumption about the shape of the baseline hazard, which is why the
selection procedure below spends its effort testing that assumption.
"""
    )

    report.heading("Variable selection").text(
        """
Covariates were chosen from credit reasoning first and tested second, not selected
by a stepwise search. A search over this many correlated covariates would find a
specification that fits this sample and would not survive the next one.

Three exclusions are deliberate and matter more than the inclusions:
"""
    ).bullets(
        [
            "**Origination vintage** is reserved for the out-of-time split. As a "
            "covariate it absorbs exactly the macroeconomic effects the model exists "
            "to estimate.",
            "**Contemporaneous macro** is excluded: every series is lagged three months, "
            "revised ones because they are published late and market quotes because a "
            "loan ninety days delinquent in a month missed its payments in the three "
            "before it. Look-ahead is invisible in results -- a model that quietly reads "
            "next quarter's unemployment looks excellent and is worthless.",
            "**Current delinquency status** is excluded as a mediator, not a "
            "predictor. Including it inflates every metric while destroying the "
            "model's actual use, which is predicting lifetime PD from origination.",
        ]
    ).text(
        """
Loan-to-value is decomposed rather than indexed. `orig_ltv` and `indexed_cltv` are
*equal* at origination and stay strongly correlated afterwards, so fitting both
gives unstable coefficients. They are split into a level -- `orig_ltv`,
underwriting quality -- and a movement -- `cltv_drift`, how far house prices have
carried the position since, zero at origination by construction.
"""
    )

    report.heading("Model selection")
    report.text(
        """
The intended centrepiece was the generalised gamma, which nests the exponential,
Weibull, gamma, log-normal and inverse-Weibull families, so that one parameter
*tests* which family the data supports rather than ranking candidates by
information criterion. **It is not usable here.**

`GeneralizedGammaRegressionFitter` does not converge on the episode panel under any
remedy tried: penalties from 0.001 to 0.1, durations rescaled, and both L-BFGS-B
and SLSQP. `GeneralizedGammaFitter` on loan-level data nominally converges but
returns a singular Hessian -- standard errors are NaN, lifelines warns against
trusting the parameters, and on data generated from a Weibull process it
estimates the shape parameter at 4.04 where the truth is 1.

An unusable test is worse than no test, so selection rests on five weaker but sound
layers instead.

**Where families nest, they are tested rather than ranked.** An information criterion
is both more expensive and weaker than a hypothesis test, and the exponential nests
inside the Weibull -- so it costs no fit at all, only a Wald test on a parameter the
Weibull fit has already estimated. Only families that genuinely do not nest cost a fit
each.
"""
    )

    exponential = exponential_is_rejected(fitted) if fitted.distribution == "weibull" else None
    if exponential is not None:
        report.heading("1. Is the hazard constant? No fit required", level=3).text(
            f"""
The exponential is a Weibull with shape one, so the constant-hazard hypothesis is
exactly `log rho = 0` and reads straight off the fitted coefficient table.

**rho = {exponential["rho"]:.4f}, z = {exponential["z"]:.0f}, p = {exponential["p_value"]:.2e}.**
The hazard {_direction(exponential["rho"])}show, and the constant-hazard hypothesis
is settled without estimating anything further.
"""
        )

    marginal = marginal_comparison(panel, weights_col=weights_col)
    report.heading("2. Marginal shape, covariate-free", level=3).text(
        """
Cheap -- seconds -- and **it does not answer the question it appears to answer.** It is
shown because the obvious reading of it is wrong, and that is worth seeing.

The marginal hazard is not the baseline hazard. On this panel it peaks at about
forty-eight months of loan age, which looks like a seasoning curve and is not: it is
2008 to 2010. Every vintage meets the crisis at a different loan age, so pooling them
smears a calendar event across the age axis and produces a hump belonging to the economy
rather than to the loan.

Slicing the data differently does not repair it, because the obstruction is structural.
Calendar period, origination cohort and loan age satisfy `period = cohort + age`
**identically**, so no two can be held fixed while the third moves. Holding the calendar
fixed at June 2009, the hazard rises to 61 bp at twenty-three months of age and falls to
8 bp at eighty -- and the twenty-three month old loans are the 2007 vintage while the
eighty month old ones are 2002. The profile tracks vintage quality exactly as well as it
tracks age.

This is the age-period-cohort identification problem, and its consequence here is that
**the shape of the baseline hazard is not identified non-parametrically at all.** It
becomes identified only under a restriction, and the restriction this model makes is
that calendar time enters through a handful of macroeconomic covariates rather than as a
free period effect. Which family fits therefore cannot be separated from which
covariates are in the model -- which is why the comparison below, made *with* them, is
the one that decides.
"""
    ).table(marginal, decimals=2)

    # `fitted` is passed through so neither of these refits the model already in
    # hand: the Weibull row of the comparison and the restricted arm of the shape
    # test are both the default specification, and at hours per fit that matters.
    regression = (
        distribution_comparison(
            encoded, covariates, formula, weights_col=weights_col, fitted=fitted
        )
        if extra_fits
        else None
    )
    report.heading("3. Regression fits on identical episodes", level=3).text(
        """
The comparison is made with the covariates, and it is a sign check as well as a ranking: a
family that fits worse and also points a declared prior the wrong way is rejected for two
independent reasons. The validation made this comparison on the specification before it,
which the published run had skipped: the log-logistic came 623,126 AIC points behind the
Weibull, 28,138,529 against 27,515,402, and turned `orig_ltv`, `term_years` and investor
occupancy around. The table is this run's own comparison, on this run's specification.

The log-normal is absent because it does not converge on this panel structure --
observed across sample sizes, with and without a penalizer, under two optimisers,
with left truncation on and off, and with durations rescaled. The cause was not
established, so none is claimed; the behaviour is pinned by a strict `xfail` that
will fail the suite if a later lifelines fixes it.

**AIC here counts episodes, not loans**, because that is the unit the likelihood
sums over. It ranks distributions on one panel and means nothing across different
panel constructions -- comparing an interval-censored episode panel with a
loan-level right-censored one by AIC is not a comparison at all.
"""
    )
    if regression is None:
        report.text(_SKIPPED.format(what="comparing distributions", flag="--extra-fits"))
    else:
        report.table(regression, decimals=2)

    relaxed, ancillary = shape_formula(covariates, CATEGORICAL_REFERENCE)
    shape = (
        shape_depends_on_covariates(
            encoded, covariates, formula, ancillary, weights_col=weights_col, fitted=fitted
        )
        if extra_fits
        else None
    )
    why = (
        ", the one covariate whose survival curves cross: investor loans default faster "
        "early and slower late, which no scale factor can represent"
        if relaxed == SHAPE_COVARIATE
        else ""
    )
    report.heading("4. Does the hazard's shape vary with covariates?", level=3).text(
        f"""
The default model lets a covariate move *when* default happens while leaving the
shape of the hazard over the life of the loan alone. That is an assumption, and a
nested one, so a likelihood ratio test can say whether relaxing it earns its keep.

It matters for lifetime PD specifically: if the shape genuinely varies, the term
structure differs by loan rather than merely shifting, and a single shape misstates
the timing of losses even when it gets the total right.

Tested on `{relaxed}`{why}:
"""
    )
    if shape is None:
        report.text(_SKIPPED.format(what="testing the shape", flag="--extra-fits"))
    else:
        report.table(shape, decimals=4)

    curve = kaplan_meier(panel, weights_col=weights_col)
    predicted = predicted_survival_curve(fitted, encoded, covariates, weights_col=weights_col)
    band = km_band_contains(curve, predicted)
    inside = int(band["inside"].sum())

    figure = charts.survival_vs_kaplan_meier(curve, predicted, figures / "survival_vs_km.png")
    report.heading("5. Against the non-parametric estimate", level=3).text(
        f"""
The strongest evidence available, because Kaplan-Meier assumes nothing about the
distribution. A fitted curve straying outside its confidence band is being
contradicted by the data rather than merely smoothing it.

**{inside} of {len(band)} points fall inside the band** -- and on this panel that
number carries almost no information, which is worth explaining rather than reporting
as a verdict.

A confidence band narrows as the square root of the sample, and on 48 million loans it
collapses. At five years this one runs from {_pct(band, 63, "km_lower")} to
{_pct(band, 63, "km_upper")} -- a width of **{_band_width(band, 63):.4f} percentage
points**, and the median across the horizon is {_median_width(band):.4f}. Every smooth
parametric curve is outside a band that narrow, so the in-or-out test answers a question
nobody is asking at this size.

The quantity that does carry information is how far the curve is from the data: **largest
deviation {_worst(band):.2f} percentage points of survival, mean {_mean_deviation(band):.2f}**,
over a horizon of {len(band)} months. That is what the comparison is for.

This check earned its place. An earlier version of the comparison predicted each
loan's curve from its origination covariates and averaged those, which put only
half the horizon inside the band and overstated five-year survival by eight
percentage points. The cause is that `cltv_drift` and `unemp_gap` are zero at
origination *by construction*, so freezing them there assumes house prices never
move and unemployment never changes. The curve below chains the monthly hazard
along each loan's realised covariate path instead.
"""
    ).figure(figure, "Fitted survival against Kaplan-Meier with its confidence band")
    report.table(
        band.reset_index(names="month").iloc[:: max(len(band) // 10, 1)],
        caption="Fitted against observed survival, sampled across the horizon",
    )

    report.heading("Fit summary").key_values(
        {
            "distribution": fitted.distribution,
            "likelihood": fitted.likelihood.value,
            "episodes": fitted.n_episodes,
            "defaults": fitted.n_events,
            "log-likelihood": fitted.log_likelihood,
            "AIC (episode scale)": fitted.aic,
            "fit seconds": fitted.elapsed_seconds,
        },
        decimals=2,
    )

    report.text(
        provenance(
            [
                "`uv run creditsurv report`",
                f"Formula: `{formula}`",
                "Loan data: Freddie Mac Single-Family Loan-Level Dataset. Macro: FRED; "
                "see `docs/data_dictionary.md`.",
            ]
        )
    )
    return report.write(reports_dir / "methodology.md")
