"""Generates the methodology and fit-quality report.

Covers why the model is specified the way it is, how the distributional form was
chosen, and how well the result fits -- including the parts of the plan that did
not survive contact with the data, since a selection procedure is only credible if
its failures are visible too.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from creditsurv.models.nonparametric import (
    kaplan_meier,
    km_band_contains,
    predicted_survival_curve,
)
from creditsurv.models.selection import (
    distribution_comparison,
    marginal_comparison,
    shape_depends_on_covariates,
)
from creditsurv.reporting import charts
from creditsurv.reporting.builder import Report, provenance

if TYPE_CHECKING:
    from collections.abc import Sequence
    from pathlib import Path

    import pandas as pd

    from creditsurv.models.aft import FitResult


def generate(
    panel: pd.DataFrame,
    encoded: pd.DataFrame,
    fitted: FitResult,
    covariates: Sequence[str],
    formula: str,
    *,
    reports_dir: Path,
    weights_col: str | None = None,
) -> Path:
    """Write ``methodology.md`` and its figures.

    ``weights_col`` names the loan-month count carried by an aggregated panel. Every
    statistic below then describes the population rather than the set of distinct
    covariate combinations, which are very different books.
    """
    figures = reports_dir / "figures"

    report = Report(
        "Methodology, variable selection and fit quality",
        subtitle="Generated by `creditsurv report`. Numbers come from the run, not the prose.",
    )

    report.heading("Why survival analysis").text(
        """
A default flag answers whether a loan defaulted. Lifetime PD needs to know *when*,
and needs an answer for the loans that have not defaulted yet -- which is most of
them. A classifier discards both: the timing, and the fact that a loan observed for
six months and still performing is evidence about the first six months only.

Survival analysis keeps both. Censoring is a first-class concept rather than a
missing label, and the output is a curve rather than a number, which is what a term
structure of losses is built from.
"""
    )

    report.heading("Why a parametric model rather than Cox").text(
        """
Lifetime PD needs three things a Cox model does not give:

1. **Extrapolation past the observation window.** A Cox baseline hazard is defined
   only where events were observed; a lifetime PD quoted over a remaining term
   longer than the data has seen requires a functional form.
2. **Response to macroeconomic scenarios.** Pushing a stressed macro path through
   the model requires a hazard that can be evaluated at covariate values that have
   not occurred.
3. **A smooth term structure.** A step function is an awkward basis for a loss
   forecast by month.

The cost is an assumption about the shape of the baseline hazard, which is why the
selection procedure below spends its effort testing that assumption.
"""
    )

    report.heading("Variable selection").text(
        """
Covariates were chosen from credit reasoning first and tested second, not selected
by a stepwise search. A search over this many correlated covariates would find a
specification that fits this sample and would not survive the next one.

Three exclusions are deliberate and matter more than the inclusions:
"""
    ).bullets(
        [
            "**Origination vintage** is reserved for the out-of-time split. As a "
            "covariate it absorbs exactly the macroeconomic effects the model exists "
            "to estimate.",
            "**Contemporaneous revised macro** is excluded; every revised series is "
            "lagged three months. Look-ahead is invisible in results -- a model that "
            "quietly reads next quarter's unemployment looks excellent and is worthless.",
            "**Current delinquency status** is excluded as a mediator, not a "
            "predictor. Including it inflates every metric while destroying the "
            "model's actual use, which is predicting lifetime PD from origination.",
        ]
    ).text(
        """
Loan-to-value is decomposed rather than indexed. `orig_ltv` and `indexed_cltv` are
*equal* at origination and stay strongly correlated afterwards, so fitting both
gives unstable coefficients. They are split into a level -- `orig_ltv`,
underwriting quality -- and a movement -- `cltv_drift`, how far house prices have
carried the position since, zero at origination by construction.
"""
    )

    report.heading("Model selection")
    report.text(
        """
The intended centrepiece was the generalised gamma, which nests the exponential,
Weibull, gamma, log-normal and inverse-Weibull families, so that one parameter
*tests* which family the data supports rather than ranking candidates by
information criterion. **It is not usable here.**

`GeneralizedGammaRegressionFitter` does not converge on the episode panel under any
remedy tried: penalties from 0.001 to 0.1, durations rescaled, and both L-BFGS-B
and SLSQP. `GeneralizedGammaFitter` on loan-level data nominally converges but
returns a singular Hessian -- standard errors are NaN, lifelines warns against
trusting the parameters, and on data generated from a Weibull process it
estimates the shape parameter at 4.04 where the truth is 1.

An unusable test is worse than no test, so selection rests on four weaker but sound
layers instead.
"""
    )

    marginal = marginal_comparison(panel, weights_col=weights_col)
    report.heading("1. Marginal shape, covariate-free", level=3).text(
        "A cheap check that catches a badly wrong family before any regression is "
        "attempted. It cannot decide the final model, because covariates change "
        "which family fits best."
    ).table(marginal, decimals=2)

    # `fitted` is passed through so neither of these refits the model already in
    # hand: the Weibull row of the comparison and the restricted arm of the shape
    # test are both the default specification, and at hours per fit that matters.
    regression = distribution_comparison(
        encoded, covariates, formula, weights_col=weights_col, fitted=fitted
    )
    report.heading("2. Regression fits on identical episodes", level=3).text(
        """
The log-normal is absent because it does not converge on this panel structure --
observed across sample sizes, with and without a penalizer, under two optimisers,
with left truncation on and off, and with durations rescaled. The cause was not
established, so none is claimed; the behaviour is pinned by a strict `xfail` that
will fail the suite if a later lifelines fixes it.

**AIC here counts episodes, not loans**, because that is the unit the likelihood
sums over. It ranks distributions on one panel and means nothing across different
panel constructions -- comparing an interval-censored episode panel with a
loan-level right-censored one by AIC is not a comparison at all.
"""
    ).table(regression, decimals=2)

    shape = shape_depends_on_covariates(
        encoded, covariates, formula, covariates[0], weights_col=weights_col, fitted=fitted
    )
    report.heading("3. Does the hazard's shape vary with covariates?", level=3).text(
        f"""
The default model lets a covariate move *when* default happens while leaving the
shape of the hazard over the life of the loan alone. That is an assumption, and a
nested one, so a likelihood ratio test can say whether relaxing it earns its keep.

It matters for lifetime PD specifically: if the shape genuinely varies, the term
structure differs by loan rather than merely shifting, and a single shape misstates
the timing of losses even when it gets the total right.

Tested on `{covariates[0]}`:
"""
    ).table(shape, decimals=4)

    curve = kaplan_meier(panel, weights_col=weights_col)
    predicted = predicted_survival_curve(fitted, encoded, covariates, weights_col=weights_col)
    band = km_band_contains(curve, predicted)
    inside = int(band["inside"].sum())

    figure = charts.survival_vs_kaplan_meier(curve, predicted, figures / "survival_vs_km.png")
    report.heading("4. Against the non-parametric estimate", level=3).text(
        f"""
The strongest evidence available, because Kaplan-Meier assumes nothing about the
distribution. A fitted curve straying outside its confidence band is being
contradicted by the data rather than merely smoothing it.

**{inside} of {len(band)} points fall inside the band.**

This check earned its place. An earlier version of the comparison predicted each
loan's curve from its origination covariates and averaged those, which put only
half the horizon inside the band and overstated five-year survival by eight
percentage points. The cause is that `cltv_drift` and `unemp_gap` are zero at
origination *by construction*, so freezing them there assumes house prices never
move and unemployment never changes. The curve below chains the monthly hazard
along each loan's realised covariate path instead.
"""
    ).figure(figure, "Fitted survival against Kaplan-Meier with its confidence band")
    report.table(
        band.reset_index(names="month").iloc[:: max(len(band) // 10, 1)],
        caption="Fitted against observed survival, sampled across the horizon",
    )

    report.heading("Fit summary").key_values(
        {
            "distribution": fitted.distribution,
            "likelihood": fitted.likelihood.value,
            "episodes": fitted.n_episodes,
            "defaults": fitted.n_events,
            "log-likelihood": fitted.log_likelihood,
            "AIC (episode scale)": fitted.aic,
            "fit seconds": fitted.elapsed_seconds,
        },
        decimals=2,
    )

    report.text(
        provenance(
            [
                "`uv run creditsurv report`",
                f"Formula: `{formula}`",
                "Loan data: Freddie Mac Single-Family Loan-Level Dataset. Macro: FRED; "
                "see `docs/data_dictionary.md`.",
            ]
        )
    )
    return report.write(reports_dir / "methodology.md")
