"""The moratorium comparison: the model with forbearance excluded, against censored.

The validation's D1 found 17% of the panel's default events were forbearance -- CARES Act
and disaster moratoria that servicers were required to report as delinquency, and that
returned to performing in 99% of cases -- rather than credit. There are two defensible ways
to take them out, they are not equivalent, and this report is where the choice between them
is made on measurement: the same specification fitted and backtested under each.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, cast

import numpy as np
import pandas as pd

from creditsurv.backtest.runner import ACCEPTANCE
from creditsurv.models.aft import coefficient_table
from creditsurv.reporting.builder import Report, provenance

if TYPE_CHECKING:
    from pathlib import Path

    from creditsurv.backtest.runner import BacktestResult
    from creditsurv.backtest.splits import Split
    from creditsurv.models.aft import FitResult


@dataclass(frozen=True)
class Outcome:
    """One policy's panel, coefficients and backtest, as the comparison reads them."""

    policy: str
    panel: dict[str, object]
    coefficients: pd.DataFrame
    backtest: dict[str, object]
    acceptance: pd.DataFrame


def outcome(policy: str, split: Split, fitted: FitResult, result: BacktestResult) -> Outcome:
    """Keep what the report needs, so the panel itself can be released before the next."""
    return Outcome(
        policy=policy,
        panel=split.describe(),
        coefficients=coefficient_table(fitted),
        backtest=result.summary(),
        acceptance=ACCEPTANCE.assess(result),
    )


def coefficient_shift(first: Outcome, second: Outcome) -> pd.DataFrame:
    """Every coefficient under both policies, and the move between them.

    The move is scaled by the two standard errors combined. The samples overlap, so this is
    a yardstick and not a test -- and at this size no test would discriminate anyway -- but
    it says whether a coefficient moved by more than its own uncertainty.
    """
    left = first.coefficients.loc[:, ["coef", "se(coef)"]]
    right = second.coefficients.loc[:, ["coef", "se(coef)"]]
    table = left.join(right, lsuffix=f" {first.policy}", rsuffix=f" {second.policy}")
    moved = table[f"coef {second.policy}"] - table[f"coef {first.policy}"]
    combined = np.sqrt(
        table[f"se(coef) {first.policy}"] ** 2 + table[f"se(coef) {second.policy}"] ** 2
    )
    table["moved"] = moved
    table["in standard errors"] = moved / combined
    return table.reset_index()


def generate(exclude: Outcome, censor: Outcome, *, reports_dir: Path) -> Path:
    """Write ``moratorium.md`` under ``reports_dir``."""
    reports_dir.mkdir(parents=True, exist_ok=True)
    report = Report(
        "Moratorium: excluded or censored",
        subtitle="Generated by `creditsurv moratorium`. Every number comes from this run.",
    )

    report.heading("The choice").text(
        """
Forbearance is not a failure to pay, and the validation found it behind 17% of the default
events. The two ways of taking it out differ in what they keep:

* **exclude** -- an accommodated month is not an event and the loan stays at risk, so the
  exposure after the moratorium, and any genuine default that follows it, are kept;
* **censor** -- observation ends at the first accommodated month, as it does at a
  modification, and the months after it are lost with the defaults among them.

The same specification is fitted and backtested under each, below.
"""
    )

    panels = pd.DataFrame([{"policy": item.policy, **item.panel} for item in (exclude, censor)])
    report.heading("The panels").table(panels, decimals=0)

    shift = coefficient_shift(exclude, censor)
    largest = shift.loc[shift["in standard errors"].abs().idxmax()]
    moved = float(cast("float", largest["in standard errors"]))
    before = float(cast("float", largest["coef exclude"]))
    after = float(cast("float", largest["coef censor"]))
    report.heading("Coefficients").text(
        f"""
The largest move is in `{largest["covariate"]}` ({largest["param"]}):
**{moved:+.1f} combined standard errors**, from {before:+.4f} to {after:+.4f}.
"""
    ).table(shift, decimals=4)

    backtests = pd.DataFrame(
        [{"policy": item.policy, **item.backtest} for item in (exclude, censor)]
    )
    acceptance = pd.concat(
        [item.acceptance.assign(policy=item.policy) for item in (exclude, censor)],
        ignore_index=True,
    )
    report.heading("Backtest").table(backtests).table(
        acceptance, caption="Against the acceptance criteria declared before either run"
    )

    report.text(
        provenance(
            [
                "`uv run creditsurv aggregate --moratorium exclude` and `--moratorium censor`",
                "`uv run creditsurv moratorium`",
            ]
        )
    )
    return report.write(reports_dir / "moratorium.md")
