"""The selection report: what ``creditsurv select`` ran, and what it chose.

Written from a :class:`creditsurv.models.procedure.SelectionRecord`, with the record's
summary beside it as JSON -- the file ``tests/test_procedure.py`` holds the configuration
to, so a specification that no longer matches the last selection fails the suite.
"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING, Final

import pandas as pd

from creditsurv.data.panel import DEFAULT_CAUSE
from creditsurv.models.procedure import MATERIALITY_THRESHOLD
from creditsurv.reporting.builder import Report, provenance

if TYPE_CHECKING:
    from pathlib import Path

    from creditsurv.models.procedure import SelectionRecord

#: The summary the configuration is tested against, written beside the report. It belongs to
#: the **published** model: see :func:`record_name`.
SUMMARY_FILE: Final = "selection.json"

#: Every table behind the report, one file each. A notebook shows these rather than
#: recomputing them: the correlation and the variance inflation read ~60 million rows of
#: expanded panel, which is the command's job, not the notebook's.
TABLE_FILES: Final[dict[str, str]] = {
    "correlation": "selection_correlation.csv",
    "collinear": "selection_collinear.csv",
    "inflation": "selection_inflation.csv",
    "screening": "selection_screening.csv",
    "elimination": "selection_elimination.csv",
    "stability": "selection_stability.csv",
    "materiality": "selection_materiality.csv",
}

#: The fits the run made, with their times and whether they came from the cache.
FITS_FILE: Final = "selection_fits.csv"


def record_name(record: SelectionRecord, *, published: str = "weibull") -> str:
    """What this run's files are called.

    ``selection`` is the **published** model's record, which ``tests/test_procedure.py``
    holds the configuration to. Every other run -- the other family, the prepayment model --
    is a record of a run rather than of the model in the configuration, and would otherwise
    overwrite it: two selections write two records, and the family rule then decides which
    one the configuration should agree with.
    """
    if record.distribution == published and record.cause == DEFAULT_CAUSE:
        return "selection"
    parts = ["selection", record.distribution]
    if record.cause != DEFAULT_CAUSE:
        parts.append(record.cause)
    return "_".join(parts)


def generate(record: SelectionRecord, *, reports_dir: Path, name: str | None = None) -> Path:
    """Write ``<name>.md`` and ``<name>.json`` under ``reports_dir``."""
    name = record_name(record) if name is None else name
    reports_dir.mkdir(parents=True, exist_ok=True)
    report = Report(
        "Variable selection, run end to end",
        subtitle="Generated by `creditsurv select`. Every number comes from this run.",
    )

    report.heading("What was run").text(
        f"""
Steps 5 to 9 of `docs/variable_selection.md`, on the training half of the whole
population up to {record.as_of}, under the `{record.moratorium}` moratorium policy:
**{record.rows:,} cells covering {record.loan_months:,.0f} loan-months**, with no sampling
at any step.

Two departures from the first run, both to keep the backtest honest. The selection sees
only the training half, because a specification chosen on the months the model is judged
on has already seen the test. And stability is judged across loans originated in even and
in odd years -- two halves that each cover every calendar month -- rather than across the
whole population and its first 94%, which needs the test window.
"""
    )

    report.heading("Chosen").text(f"`{record.selected.formula}`")
    eliminated = pd.DataFrame(
        sorted(record.eliminated.items()), columns=["covariate", "why it was removed"]
    )
    if eliminated.empty:
        report.text("Nothing was eliminated.")
    else:
        report.table(eliminated, caption="Every candidate removed, with the step and the reason")

    report.heading("5. Weighted correlation", level=3)
    if record.collinear.empty:
        report.text("No pair of candidates is correlated beyond 0.8.")
    else:
        report.table(record.collinear, caption="Pairs beyond 0.8, reported and not resolved")

    report.heading("6. Variance inflation", level=3)
    if record.inflation.empty:
        report.text("No candidate's variance inflation reaches 10.")
    else:
        report.table(record.inflation, caption="Removed one at a time, in the fixed priority")

    report.heading("7. Univariate screening", level=3).text(
        """
Each candidate fitted beside the loan block. At this sample size every p-value is zero, so
the screen cannot discard anything on significance; what the table carries is the sign
against its expected direction, the effect of one standard deviation on log survival
time, and the likelihood ratio the candidate earns.
"""
    ).table(record.screening)

    report.heading("8. Backward elimination", level=3)
    if record.elimination.empty:
        report.text("Every survivor of the screen kept its expected sign.")
    else:
        report.table(record.elimination, caption="One covariate a step, a backwards sign first")

    report.heading("9. Stability", level=3).text(
        """
The survivors fitted on the whole training half and on each half of the book. A covariate
whose standardised effect changes sign between them, beside a larger covariate of the same
economic dimension, carries information the model already has and is not identified.
An unstable covariate with no such partner is kept, and left visible here.
"""
    )
    if record.stability.empty:
        report.text("Stability was not run.")
    else:
        report.table(record.stability)

    report.heading("10. Materiality", level=3).text(
        f"""
A macro covariate whose effect of one standard deviation on log survival time is under
{MATERIALITY_THRESHOLD:g} in absolute value contributes its sign and little else, and a covariate
that small changes sign when the sample does. The threshold is fixed in `docs/rules.md`,
before any of these fits, and the removals are made one at a time because each one moves
every other coefficient.
"""
    )
    if record.materiality.empty:
        report.text("Every covariate that survived step 9 clears the threshold.")
    else:
        report.table(record.materiality, caption="One covariate a step, the smallest first")

    fits = pd.DataFrame(record.fits)
    if not fits.empty:
        report.heading("Fits").table(
            fits.loc[:, ["sample", "formula", "minutes", "evaluations", "cached"]],
            caption="Every model estimated, in order; cached ones were read from an earlier run",
            decimals=1,
        )

    report.text(
        provenance(
            [
                f"`uv run creditsurv select --as-of {record.as_of} "
                f"--moratorium {record.moratorium} --dist {record.distribution}"
                + (f" --cause {record.cause}`" if record.cause != DEFAULT_CAUSE else "`"),
                "Procedure: `creditsurv.models.procedure.run_selection`",
            ]
        )
    )
    (reports_dir / f"{name}.json").write_text(
        json.dumps(record.summary(), indent=2, sort_keys=True) + "\n"
    )
    for attribute, filename in TABLE_FILES.items():
        table: pd.DataFrame = getattr(record, attribute)
        table.to_csv(
            reports_dir / filename.replace("selection", name, 1), index=attribute == "correlation"
        )
    pd.DataFrame(record.fits).to_csv(
        reports_dir / FITS_FILE.replace("selection", name, 1), index=False
    )
    return report.write(reports_dir / f"{name}.md")
