"""Three cuts, one multiplier, eight grades: the backtest the validation asked for.

The previous model was cut once, at 2024-12, and judged on fifteen quiet months. Its
out-of-time actual over expected was 0.920 -- read alone, an encouraging number, and it sat
inside an in-sample spread of 0.47 to 1.60 by calendar year, which is the observation that
made this report necessary.

What is here, all of it declared in `docs/rules.md` before the runs that fill it:

* **three windows**, cut at the end of 2018, 2020 and 2022, each estimated on everything up
  to its own cut and judged on the 24 months after it -- a tightening cycle, a pandemic under
  a moratorium regime, and a rate shock. Each window is closed, or the 2018 model would be
  judged on the pandemic as well and the three would not be three regimes;
* **the in-sample cycle**, the share of calendar years whose actual over expected falls
  inside 0.80 to 1.25, which is the dispersion a single out-of-time ratio hides;
* **one multiplier** on the default hazard, estimated as actual over expected on 2022-01 to
  2024-12 and applied to every loan-month, with the test window scored before and after it.
  The coefficients, the shape and the ranking are untouched;
* **eight grades** of twelve-month PD on geometric thresholds, each judged against the 95%
  Jeffreys interval around what its loans did.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from creditsurv.backtest.metrics import master_scale_passed
from creditsurv.backtest.runner import ACCEPTANCE, BACKTEST_WINDOW_MONTHS
from creditsurv.reporting.builder import Report, provenance

if TYPE_CHECKING:
    from collections.abc import Sequence
    from pathlib import Path

    import pandas as pd

    from creditsurv.models.anchoring import Anchor


def generate(
    windows: pd.DataFrame,
    *,
    cycle: pd.DataFrame,
    anchor: Anchor,
    level: pd.DataFrame,
    grades: pd.DataFrame,
    acceptance: Sequence[pd.DataFrame],
    reports_dir: Path,
) -> Path:
    """Write ``windows.md`` under ``reports_dir``."""
    reports_dir.mkdir(parents=True, exist_ok=True)
    report = Report(
        "Windows, anchoring and grades",
        subtitle="Generated by `creditsurv windows`. Every number comes from this run.",
    )

    report.heading("Three cuts, each judged on what came next").text(
        f"""
Each row is a model estimated on everything up to its cut and scored on the
{BACKTEST_WINDOW_MONTHS} months after it, so no window is scored by a model that saw it. The
windows are closed for the same reason they are three: judged on everything after it, the
2018 model would be judged on the pandemic too.
"""
    ).table(windows, caption="One fit per cut, warm-started from the cut before")

    report.heading("The cycle, in sample").text(
        """
The criterion the previous model was not tested against. A single out-of-time ratio near one
says nothing beside the spread across calendar years, and the previous model's ran from 0.47
to 1.60.
"""
    ).table(cycle, caption="Calendar years inside 0.80 to 1.25, in sample")

    report.heading("The level, anchored on 2022-24").text(
        f"""
One multiplier of **{anchor.multiplier:.4f}** on the default hazard, estimated as actual over
expected on {anchor.window[0]} to {anchor.window[1]} -- {anchor.actual_defaults:,.0f} defaults
against {anchor.expected_defaults:,.0f} expected over {anchor.loan_months:,.0f} loan-months --
and applied to every loan-month. Nothing else changes: not the coefficients, not the shape of
the hazard, not the ranking, so discrimination is unchanged by construction and the segment
views still mean something.

The window is the anchoring window and nothing else. Estimation ends 2021-12 and the test
window opens 2025-01, so the level is set on months the coefficients never saw and scored on
months the level never saw.
"""
    ).table(level, caption="The test window before and after the multiplier")

    passed = master_scale_passed(grades)
    report.heading("Twelve-month PD by grade").text(
        f"""
Eight grades on geometric thresholds of predicted twelve-month PD, each floor twice the one
before. A grade passes when its predicted PD falls inside the 95% Jeffreys interval around
the rate its loans realised -- Jeffreys because the top grades hold few defaults and
sometimes none, where a normal interval has no width and no grade can fail.

**The scale {"passes" if passed else "fails"}**: {int(grades["passed"].sum())} of
{len(grades)} populated grades hold, against the seven of eight the rule asks for.
"""
    ).table(grades, caption="Predicted against realised, in obligor-years", decimals=6)

    report.heading("The criteria")
    for table in acceptance:
        report.table(table)

    report.text(
        provenance(
            [
                "`uv run creditsurv windows`",
                "Rules: `docs/rules.md`, sections 1, 4, 5 and 7",
                f"Criteria: actual over expected {ACCEPTANCE.ae_low:.2f} to "
                f"{ACCEPTANCE.ae_high:.2f}, Gini above {ACCEPTANCE.gini_min:.2f}",
            ]
        )
    )
    return report.write(reports_dir / "windows.md")
